DROP TABLE xxbcm_order_mgt CASCADE CONSTRAINTS;
------------- // CREATING DB_Prequisite TABLE //------------- 
  CREATE TABLE XXBCM_ORDER_MGT 
   (	
	ORDER_REF 			VARCHAR2(2000), 
	ORDER_DATE 			VARCHAR2(2000), 
	SUPPLIER_NAME 		VARCHAR2(2000), 
	SUPP_CONTACT_NAME 	VARCHAR2(2000), 
	SUPP_ADDRESS 		VARCHAR2(2000), 
	SUPP_CONTACT_NUMBER VARCHAR2(2000), 
	SUPP_EMAIL 			VARCHAR2(2000), 
	ORDER_TOTAL_AMOUNT 	VARCHAR2(2000), 
	ORDER_DESCRIPTION 	VARCHAR2(2000), 
	ORDER_STATUS 		VARCHAR2(2000), 
	ORDER_LINE_AMOUNT 	VARCHAR2(2000), 
	INVOICE_REFERENCE 	VARCHAR2(2000), 
	INVOICE_DATE 		VARCHAR2(2000), 
	INVOICE_STATUS 		VARCHAR2(2000), 
	INVOICE_HOLD_REASON VARCHAR2(2000), 
	INVOICE_AMOUNT 		VARCHAR2(2000), 
	INVOICE_DESCRIPTION VARCHAR2(2000)
   ) ;
SET DEFINE OFF

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO001', '03-JAN-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 5741254S', 'geonee@pegasus.mu', '10,000', 'Vehicle Spare parts', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO001-1', '03-JAN-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 5741254S', 'geonee@pegasus.mu', NULL, 'Back lights', 'Received', '2,500', 'INV_PO001', '28-FEB-2017', 'Paid', NULL, '25oo', 'Part payment for vehicle spare parts');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO001-2', '03-JAN-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 5741254S', 'geonee@pegasus.mu', NULL, 'Spark plug', 'Received', '600', 'INV_PO001', '28-FEB-2017', 'Paid', NULL, '600', 'Part payment for vehicle spare parts');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO002', '10-JAN-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', '750000', 'Purchase of Car', 'Open', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO002-1', '10-JAN-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', NULL, 'Purchase of Car Model X', 'Received', '10000o', 'INV_PO002.1', '01-MAR-2017', 'Paid', NULL, '100000', 'Part payment for purchase of car');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO003', '24-JAN-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 602801o', 'bparker@intnet.mu', '57300', 'Computer screens', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO003-1', '24-JAN-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'Screens 22"', 'Received', '22000', 'INV_PO003.1', '22-MAR-2017', 'Paid', NULL, '22,000', 'Purchase of screens.');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO003-2', '24-JAN-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 602801o', 'bparker@intnet.mu', NULL, 'Screens 35"', 'Received', '20300', 'INV_PO003.1', '22-MAR-2017', 'Paid', NULL, '20300', 'Purchase of screens.');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO003-3', '24-JAN-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'Screens 15"', 'Received', 'S,000', 'INV_PO003.1', '22-MAR-2017', 'Paid', NULL, '5000', 'Purchase of screens.');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO001-3', '03-JAN-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Fuel filter', 'Received', '2000', 'INV_PO001', '28-FEB-2017', 'Paid', NULL, '2,000', 'Part payment for vehicle spare parts');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO004', '07-FEB-2017', 'LAMBONI STAT INC.', 'Frederic Pey', '9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses', '52557435.', 'manustat@gmail.com', '6800', 'Purchase of Stationeries', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO004-1', '07-FEB-2017', 'LAMBONI STAT INC.', 'Frederic Pey', '9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses', '52557435.', 'manustat@gmail.com', '2,000', 'Pen Parker blue', 'Received', '2000', 'INV_PO004', '15-FEB-2017', 'Paid', NULL, '2,000', 'Payment for pen');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO004-2', '07-FEB-2017', 'LAMBONI STAT INC.', 'Frederic Pey', '9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses', '52557435.', 'manustat@gmail.com', '2,000', 'Pencil HB boxes', 'Received', 'I200', 'INV_PO004', '15-FEB-2017', 'Paid', NULL, 'I200', 'Payment for pencil');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO001-4', '03-JAN-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Air filter', 'Received', '800', 'INV_PO001', '28-FEB-2017', 'Paid', NULL, '800', 'Part payment for vehicle spare parts');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO002-1', '10-JAN-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', NULL, 'Purchase of Car Model X', 'Received', '300,000', 'INV_PO002.2', '02-MAY-2017', 'Paid', NULL, '300,000', 'Part payment for purchase of car');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO005', '07-APR-2017', 'EMTELLO LTD', 'Megan Hembly', '998, Bistrop Street, Marlone, Pamplemousses, Mauritius', '2420641, 57841698.', 'mhem@my-t.mu', '21000', 'International Magazines', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO005-1', '07-APR-2017', 'EMTELLO LTD', 'Megan Hembly', '998, Bistrop Street, Marlone, Pamplemousses, Mauritius', '2420641, 57841698.', 'mhem@my-t.mu', NULL, 'National geo nature', 'Received', '3,000', 'INV_PO005.1', '18-MAY-2017', 'Pending', 'Damaged magazine', '3,000', NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO005-2', '07-APR-2017', 'EMTELLO LTD', 'Megan Hembly', '998, Bistrop Street, Marlone, Pamplemousses, Mauritius', '2420641, 57841698.', 'mhem@my-t.mu', NULL, 'Science world', 'Received', '5000', 'INV_PO005.1', '18-MAY-2017', 'Paid', NULL, '5000', NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO003-4', '24-JAN-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'Screens 35"', 'Received', '10,000', 'INV_PO003.2', '15-MAY-2017', 'Paid', NULL, '10,000', 'Final payment for purchase of screens.');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO002-1', '10-JAN-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', NULL, 'Purchase of Car Model X', 'Received', '249000', 'INV_PO002.3', '05-AUG-2017', 'Pending', NULL, '249000', 'Final payment for purchase of car');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO004-3', '07-FEB-2017', 'LAMBONI STAT INC.', 'Frederic Pey', '9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses', '52557435.', 'manustat@gmail.com', '3000', 'Paper reams', 'Received', '3,000', 'INV_PO004.1', '20-MAR-2017', 'Paid', NULL, '3000', 'Paper reams.');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO004-4', '07-FEB-2017', 'LAMBONI STAT INC.', 'Frederic Pey', '9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses', '52557435.', 'manustat@gmail.com', '600', 'Clips boxes', 'Cancelled', '600', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO005-3', '07-APR-2017', 'EMTELLO LTD', 'Megan Hembly', '998, Bistrop Street, Marlone, Pamplemousses, Mauritius', '2420641, 57841698.', 'mhem@my-t.mu', NULL, 'Science world', 'Received', '8000', 'INV_PO005.2', '22-JUN-2017', 'Paid', NULL, '8000', NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO005-4', '07-APR-2017', 'EMTELLO LTD', 'Megan Hembly', '998, Bistrop Street, Marlone, Pamplemousses, Mauritius', '2420641, 57841698.', 'mhem@my-t.mu', NULL, 'Discovery mag', 'Received', '5000', 'INV_PO005.2', '22-JUN-2017', 'Paid', NULL, 'S000', NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO001-5', '03-JAN-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Brake disc', 'Received', '3,000', 'INV_PO001.1', '04-APR-2017', 'Paid', NULL, '3000', 'Final payment for vehicle spare parts');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO001-6', '03-JAN-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Axle', 'Received', '1100', 'INV_PO001.1', '04-APR-2017', 'Paid', NULL, '1100', 'Final payment for vehicle spare parts');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO006', '16-FEB-2017', 'STUFFIE STATIONERY', 'Zenhir Belall', '67, Bistro Route, Heneral Street, Vacaoas, Mauritius', '6547416', 'info@sstat.com', '250000', 'Stationery orders', 'Open', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO006-1', '16-FEB-2017', 'STUFFIE STATIONERY', 'Zenhir Belall', '67, Bistro Route, Heneral Street, Vacaoas, Mauritius', '6547416', 'info@sstat.com', NULL, 'Packet 1', 'Received', '24300', 'INV_PO006.1', '22-MAR-2017', 'Paid', NULL, '24300', 'First delivery');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO007', '03-06-2017', 'SAFEDEST TAXI SERVICES', 'Steeve Narsimullu', '-, Le clezio street, Barbley wood, Highlands, Mauritius', '5874 1002, 217 4512', 'steeve.nar@safedest.mu', '26700', 'Taxi services fees', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO008', '05-JUN-2017', 'JINFIX COMPUTERS', 'Jordan Liu Min', '93, Bardeau lane, - , Port Louis, Mauritius', '58412556,2195412', 'contactus@jinfixcomputers.com', '85200', 'Orders of computer spare parts', 'Open', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO008-1', '05-JUN-2017', 'JINFIX COMPUTERS', 'Jordan Liu Min', '93, Bardeau lane, - , Port Louis, Mauritius', '58412556,2195412', 'contactus@jinfixcomputers.com', NULL, '10 HDDs 3TB', 'Received', '3025o', 'INV_PO008.1', '02-AUG-2017', 'Paid', NULL, '15250', 'Computer oders invoice - 1');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO008-2', '05-JUN-2017', 'JINFIX COMPUTERS', 'Jordan Liu Min', '93, Bardeau lane, - , Port Louis, Mauritius', '58412556,2195412', 'contactus@jinfixcomputers.com', NULL, '10 Motherboard Asus PRIME Z270-A', 'Received', '48000', 'INV_PO008.1', '02-AUG-2017', 'Paid', NULL, '25000', 'Computer oders invoice - 1');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO009', '18-JUN-2017', 'FIRELAND BROS.', 'Amelia Bridney', '-, Main court bldg, Nerling road, Moka, Mauritius', '5948 0015', 'abridney@gmail.com', '36800', 'Security vests', 'Open', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO009-1', '18-JUN-2017', 'FIRELAND BROS.', 'Amelia Bridney', '-, Main court bldg, Nerling road, Moka, Mauritius', '5948 0015', 'abridney@gmail.com', NULL, 'Security vests for firewardens', 'Received', '22500', 'INV_PO009.1', '24-AUG-2017', 'Paid', NULL, '22,500', 'Security vests');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO010', '03-JUL-2017', 'FOXY ELECTRONICS', 'Reddy Floyd', 'C47, Green Street, -, Savanne, Mauritius', '5284 5412', 'foxyelec@yahoo.fr', '182,700', 'Electronic spare parts', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO010-1', '03-JUL-2017', 'FOXY ELECTRONICS', 'Reddy Floyd', 'C47, Green Street, -, Savanne, Mauritius', '5284 5412', 'foxyelec@yahoo.fr', NULL, 'Electronic Component Lead 2000 Kgs', 'Received', '98000', 'INV_PO010.1', '15-AUG-2017', 'Paid', NULL, '98,000', 'Electronic spare parts - Inv 1');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO010-1', '03-JUL-2017', 'FOXY ELECTRONICS', 'Reddy Floyd', 'C47, Green Street, -, Savanne, Mauritius', '5284 5412', 'foxyelec@yahoo.fr', NULL, 'Air Conditioner Fan Capacitor x 1000', 'Received', '17500', 'INV_PO010.1', '15-AUG-2017', 'Paid', NULL, '17,500', 'Electronic spare parts - Inv 1');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO010-2', '03-JUL-2017', 'FOXY ELECTRONICS', 'Reddy Floyd', 'C47, Green Street, -, Savanne, Mauritius', '5284 5412', 'foxyelec@yahoo.fr', NULL, 'Aluminium LED PCB Assemblies x 100', 'Received', '28,000', 'INV_PO010.1', '02-SEP-2017', 'Paid', NULL, '28000', 'Electronic spare parts - Inv 2');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO010-2', '03-JUL-2017', 'FOXY ELECTRONICS', 'Reddy Floyd', 'C47, Green Street, -, Savanne, Mauritius', '5284 5412', 'foxyelec@yahoo.fr', NULL, 'Starter capacitor x 2000', 'Received', '18200', 'INV_PO010.1', '02-09-2017', 'Paid', NULL, '18200', 'Electronic spare parts - Inv 2');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO010-3', '03-07-2017', 'FOXY ELECTRONICS', 'Reddy Floyd', 'C47, Green Street, -, Savanne, Mauritius', '5284 5412', 'foxyelec@yahoo.fr', NULL, 'Block connector universal x 200', 'Received', '2I,000', 'INV_PO010.1', '15-AUG-2017', 'Paid', NULL, '21000', 'Electronic spare parts - Inv 1');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO011', '06-07-2017', 'LAMBONI STAT INC.', 'Frederic Pey', '9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses', '52557435.', 'manustat@gmail.com', '43200', 'Purchase of Stationeries', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO011-1', '06-JUL-2017', 'LAMBONI STAT INC.', 'Frederic Pey', '9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses', '52557435.', 'manustat@gmail.com', NULL, 'Staplers Heavy duty x 10', 'Received', '3200', 'INV_PO011.1', '18-SEP-2017', 'Paid', NULL, '3,200', 'Stationeries');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO008-1', '05-JUN-2017', 'JINFIX COMPUTERS', 'Jordan Liu Min', '93, Bardeau lane, - , Port Louis, Mauritius', '58412556,2195412', 'contactus@jinfixcomputers.com', NULL, '10 HDDs 3TB', 'Received', '30250', 'INV_PO008.2', '28-08-2017', 'Paid', NULL, '15,000', 'Computer oders invoice - 2');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO008-2', '05-JUN-2017', 'JINFIX COMPUTERS', 'Jordan Liu Min', '93, Bardeau lane, - , Port Louis, Mauritius', '58412556,2195412', 'contactus@jinfixcomputers.com', NULL, '10 Motherboard Asus PRIME Z270-A', 'Received', '48000', 'INV_PO008.2', '28-AUG-2017', 'Paid', NULL, '23000', 'Computer oders invoice - 2');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO006-1', '16-FEB-2017', 'STUFFIE STATIONERY', 'Zenhir Belall', '67, Bistro Route, Heneral Street, Vacaoas, Mauritius', '6547416', 'info@sstat.com', NULL, 'Packet 3', 'Received', '25,400', 'INV_PO006.3', '21-MAY-2017', 'Paid', NULL, '25,400', 'Third delivery');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO011-2', '06-JUL-2017', 'LAMBONI STAT INC.', 'Frederic Pey', '9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses', '52557435.', 'manustat@gmail.com', NULL, 'Organizers x 200', 'Received', '40000', 'INV_PO011.1', '18-SEP-2017', 'Paid', NULL, '40000', 'Stationeries');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', '265000', 'Vehicle Spare parts', 'Open', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-1', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Aluminium evaporator x 15', 'Received', '3,4S0', 'INV_PO012.1', '07-AUG-2017', 'Paid', NULL, '3,450', 'Vehicle spare parts - Part Pay 1');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO006-1', '16-FEB-2017', 'STUFFIE STATIONERY', 'Zenhir Belall', '67, Bistro Route, Heneral Street, Vacaoas, Mauritius', '6547416', 'info@sstat.com', NULL, 'Packet 4', 'Received', '50200', 'INV_PO006.4', '17-06-2017', 'Paid', NULL, '50200', 'Fourth delivery');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO008-2', '05-JUN-2017', 'JINFIX COMPUTERS', 'Jordan Liu Min', '93, Bardeau lane, - , Port Louis, Mauritius', '58412556,2195412', 'contactus@jinfixcomputers.com', NULL, 'Seagate Barracuda 2TB SATA Hard Drive', 'Received', '6,950', 'INV_PO008.2', '28-AUG-2017', 'Paid', NULL, '6,950', 'Vehicle spare parts - Part Pay 2');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-1', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Wheels and balancing', 'Received', '40000', 'INV_PO012.2', '04-09-2017', 'Paid', NULL, '40000', 'Vehicle spare parts - Part Pay 2');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-2', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Servicing of cars', 'Received', '37800', 'INV_PO012.1', '07-AUG-2017', 'Paid', NULL, '37800', 'Vehicle spare parts - Part Pay 1');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-2', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Dashboard for cards', 'Received', '12,500', 'INV_PO012.2', '04-SEP-2017', 'Paid', NULL, '12,500', 'Vehicle spare parts - Part Pay 2');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-2', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Rear door + repair', 'Received', '28000', 'INV_PO012.3', '29-SEP-2017', 'Paid', NULL, '28000', 'Vehicle spare parts - Part Pay 3');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-3', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'High pressure fuel injector nozzle OEM x 10', 'Received', '7250', 'INV_PO012.1', '07-AUG-2017', 'Paid', NULL, '7250', 'Vehicle spare parts - Part Pay 1');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-4', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Air suspension compressor x 3', 'Received', '55,870', 'INV_PO012.2', '04-SEP-2017', 'Paid', NULL, '55,870', 'Vehicle spare parts - Part Pay 2');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-5', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Aluminium alloy set x 5', 'Received', '43750', 'INV_PO012.3', '29-SEP-2017', 'Paid', NULL, '43750', 'Vehicle spare parts - Part Pay 3');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-5', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Master brake x 12', 'Received', '12600', 'INV_PO012.3', '29-SEP-2017', 'Paid', NULL, '12600', 'Vehicle spare parts - Part Pay 3');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO006-1', '16-02-2017', 'STUFFIE STATIONERY', 'Zenhir Belall', '67, Bistro Route, Heneral Street, Vacaoas, Mauritius', '6547416', 'info@sstat.com', NULL, 'Packet 5', 'Received', '70800', 'INV_PO006.5', '27-JUL-2017', 'Paid', NULL, '70800', 'Fifth delivery');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO013', '20-AUG-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', '581,9625', 'Purchase of Cars', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO013-1', '20-08-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', NULL, 'Audi Q5', 'Received', '145,2500', 'INV_PO013.1', '28-SEP-2017', 'Paid', NULL, '145,2500', 'Car purchase');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO013-2', '20-AUG-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', NULL, 'Audi Q7', 'Received', '1974000', 'INV_PO013.1', '28-09-2017', 'Paid', NULL, '1974000', 'Car purchase');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO013-3', '20-AUG-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', NULL, 'Chevrolet Equinox', 'Received', '130,2000', 'INV_PO013.1', '28-SEP-2017', 'Paid', NULL, '130,2000', 'Car purchase');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO013-4', '20-AUG-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', NULL, 'Hyundai Tucson', 'Received', '1091125', 'INV_PO013.1', '28-SEP-2017', 'Paid', NULL, '1091125', 'Car purchase');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO006-1', '16-FEB-2017', 'STUFFIE STATIONERY', 'Zenhir Belall', '67, Bistro Route, Heneral Street, Vacaoas, Mauritius', '6547416', 'info@sstat.com', NULL, 'Packet 6', 'Received', '60,000', 'INV_PO006.6', '16-08-2017', 'Paid', NULL, '60,000', 'Sixth delivery');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO007-1', '03-JUN-2017', 'SAFEDEST TAXI SERVICES', 'Steeve Narsimullu', '-, Le clezio street, Barbley wood, Highlands, Mauritius', '5874 1002, 2I7 4512', 'steeve.nar@safedest.mu', NULL, 'Employee journey taxi service', 'Received', '4,500', 'INV_PO007.1', '30-JUL-2017', 'Paid', NULL, '4500', 'Trip for Saunders');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO007-2', '03-JUN-2017', 'SAFEDEST TAXI SERVICES', 'Steeve Narsimullu', '-, Le clezio street, Barbley wood, Highlands, Mauritius', '5874 1002, 2I7 4512', 'steeve.nar@safedest.mu', NULL, 'Employee journey taxi service', 'Received', '4200', 'INV_PO007.1', '30-JUL-2017', 'Paid', NULL, '4200', 'Trip for Mike');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO007-3', '03-JUN-2017', 'SAFEDEST TAXI SERVICES', 'Steeve Narsimullu', '-, Le clezio street, Barbley wood, Highlands, Mauritius', '5874 1002, 2I7 4512', 'steeve.nar@safedest.mu', NULL, 'Employee journey taxi service', 'Cancelled', '5200', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO007-4', '03-JUN-2017', 'SAFEDEST TAXI SERVICES', 'Steeve Narsimullu', '-, Le clezio street, Barbley wood, Highlands, Mauritius', '5874 1002, 2I7 4512', 'steeve.nar@safedest.mu', NULL, 'Employee journey taxi service', 'Received', '4,800', 'INV_PO007.1', '30-JUL-2017', 'Paid', NULL, '4800', 'Trip for Shobnee');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO007-5', '03-JUN-2017', 'SAFEDEST TAXI SERVICES', 'Steeve Narsimullu', '-, Le clezio street, Barbley wood, Highlands, Mauritius', '5874 1002, 2I7 4512', 'steeve.nar@safedest.mu', NULL, 'Employee journey taxi service', 'Received', '3700', 'INV_PO007.1', '30-07-2017', 'Paid', NULL, '3700', 'Trip for Mikaen');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO006-1', '16-FEB-2017', 'STUFFIE STATIONERY', 'Zenhir Belall', '67, Bistro Route, Heneral Street, Vacaoas, Mauritius', '6547416', 'info@sstat.com', NULL, 'Packet 2', 'Received', '4300', 'INV_PO006.2', '18-04-2017', 'Paid', NULL, '4300', 'Second delivery');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', '400,120', 'Purchases of Digital equipment', 'Open', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-1', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, '2.5 EXTERNAL TOSHIBA 1TB HARD DISK USB 3.0 x 2', 'Received', '5,600', 'INV_PO014.1', '03-OCT-2017', 'Paid', NULL, '5,600', 'Invoice payment SN#001');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-2', '15-09-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, '2.5 EXTERNAL TOSHIBA 2TB HARD DISK USB 3.0 x 3', 'Received', '13250', 'INV_PO014.2', '15-OCT-2017', 'Paid', NULL, '13250', 'Invoice payment SN#002');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-3', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'NOTEBOOK SATA HDD - 500 GB x 5', 'Received', '10,000', 'INV_PO014.2', '15-OCT-2017', 'Paid', NULL, '10,000', 'Invoice payment SN#002');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-4', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, '3TB SATA HARD DISK x 4', 'Received', '15900', 'INV_PO014.3', '27-10-2017', 'Paid', NULL, '15900', 'Invoice payment SN#003');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-5', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'WESTERN DIGITAL USB 3.0 EXTERNAL HARD DISK 3.5 4TB x 2', 'Received', '13850', 'INV_PO014.4', '05-NOV-2017', 'Pending', '1 faulty HD to return before payment', '13850', 'Invoice payment SN#004');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-1', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'FAN UNIT x 20', 'Cancelled', '800', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-1', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'EPSON EB-S31 3LCD PROJECTOR x 3', 'Received', '54,850', 'INV_PO014.3', '27-OCT-2017', 'Paid', NULL, '54,850', 'Invoice payment SN#003');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-2', '15-09-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'VIEWSONIC PJD5155 PROJECTOR', 'Received', '17300', 'INV_PO014.1', '03-OCT-2017', 'Paid', NULL, '17300', 'Invoice payment SN#001');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-2', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'COOLER MASTER SEIDON120V V3 PLUS WATER-COOLING KIT x 5', 'Received', '13500', 'INV_PO014.1', '03-OCT-2017', 'Paid', NULL, '13500', 'Invoice payment SN#001');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-3', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'GENIUS MEDIA POINTER 900BT x 3', 'Received', '4275', 'INV_PO014.1', '03-OCT-2017', 'Paid', NULL, '4275', 'Invoice payment SN#001');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-3', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'USB WIRELESS <<T>> LASER POINTER PRESENTER x 2', 'Received', '900', 'INV_PO014.3', '27-OCT-2017', 'Pending', 'Pointers not compatible with system', '900', 'Invoice payment SN#003');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-3', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'ASUS H110M-A (INTEL H110) DDR4 LGA1151 MATX x 4', 'Received', '17,600', 'INV_PO014.4', '05-NOV-2017', 'Paid', NULL, '17,600', 'Invoice payment SN#004');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-3', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'ASUS B150M-K DDR4 (INTEL B150) LGA1151 MATX x 2', 'Received', '11900', 'INV_PO014.4', '05-11-2017', 'Paid', NULL, '11900', 'Invoice payment SN#004');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-4', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'ASUS H81M-A (INTEL H81) LGA1150 MATX x 2', 'Received', '7920', 'INV_PO014.1', '03-OCT-2017', 'Paid', NULL, '7920', 'Invoice payment SN#001');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-4', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'HP ADVANTAGE 4535 ALL-IN-ONE INKJET PRINTER', 'Received', '3550', 'INV_PO014.2', '15-OCT-2017', 'Pending', NULL, '3550', 'Invoice payment SN#002');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-4', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'HP M277DW WIFI COLOUR LASERJET PRO MFP', 'Received', '15,200', 'INV_PO014.1', '03-OCT-2017', 'Paid', NULL, '15,200', 'Invoice payment SN#001');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-5', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'HP OFFICEJET PRO 6830 E-ALL-IN-ONE PRINTER', 'Received', '5300', 'INV_PO014.3', '27-OCT-2017', 'Paid', NULL, '5300', 'Invoice payment SN#003');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-5', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'EPSON LQ310 DOT MATRIX PRINTER', 'Received', '12125', 'INV_PO014.3', '27-OCT-2017', 'Paid', NULL, '12125', 'Invoice payment SN#003');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-5', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'LENOVO B50-30 x 5', 'Received', '72500', 'INV_PO014.1', '03-OCT-2017', 'Pending', NULL, '72500', 'Invoice payment SN#001');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-5', '15-09-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'DELL N3543 CORE i5 x 3', 'Cancelled', '103,800', NULL, NULL, NULL, NULL, NULL, NULL);

commit;  
   
   
------------- // GENERAL //------------- 
SELECT DISTINCT * FROM xxbcm_order_mgt ORDER BY order_ref;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM USER_CONSTRAINTS; -- show all constraints in the whole database

------------- // DROPPING TABLES //------------- 
DROP TABLE supplier CASCADE CONSTRAINTS;
DROP TABLE invoice_issued CASCADE CONSTRAINTS;
DROP TABLE invoice_details CASCADE CONSTRAINTS;
DROP TABLE invoice_stats CASCADE CONSTRAINTS;
DROP TABLE order_issued CASCADE CONSTRAINTS;
DROP TABLE order_details CASCADE CONSTRAINTS;
DROP TABLE order_stats CASCADE CONSTRAINTS;

------------- // Replace non-numerical values with numerical values in amount, and removing . and , //------------- 
UPDATE xxbcm_order_mgt 
SET 
    supp_contact_number = REPLACE(supp_contact_number, '.', ''),
    order_total_amount = REPLACE(order_total_amount, ',', ''),
    order_line_amount = REPLACE(order_line_amount, ',', ''),
    invoice_amount = REPLACE(invoice_amount, ',', '');

UPDATE xxbcm_order_mgt 
SET 
    supp_contact_number = REPLACE(supp_contact_number, 'o', '0'),
    order_total_amount = REPLACE(order_total_amount, 'o', '0'),
    order_line_amount = REPLACE(order_line_amount, 'o', '0'),
    invoice_amount = REPLACE(invoice_amount, 'o', '0');
    
UPDATE xxbcm_order_mgt 
SET 
    supp_contact_number = REPLACE(supp_contact_number, 'S', '5'),
    order_total_amount = REPLACE(order_total_amount, 'S', '5'),
    order_line_amount = REPLACE(order_line_amount, 'S', '5'),
    invoice_amount = REPLACE(invoice_amount, 'S', '5');
    
UPDATE xxbcm_order_mgt 
SET 
    supp_contact_number = REPLACE(supp_contact_number, 'I', '1'),
    order_total_amount = REPLACE(order_total_amount, 'I', '1'),
    order_line_amount = REPLACE(order_line_amount, 'I', '1'),
    invoice_amount = REPLACE(invoice_amount, 'I', '1');


------------- // ALTER DATE COLUMN FROM VARCHER2 TO DATE DATA TYPE //------------- 
ALTER TABLE xxbcm_order_mgt ADD (new_order_date DATE); -- adding a new column new_order_date
ALTER TABLE xxbcm_order_mgt ADD (new_invoice_date DATE); -- adding a new column new_invoice_date
ALTER TABLE xxbcm_order_mgt ADD (new_order_status VARCHAR(10)); 
ALTER TABLE xxbcm_order_mgt ADD (new_invoice_status VARCHAR(10));
ALTER TABLE xxbcm_order_mgt ADD (new_order_total_amount NUMBER);
ALTER TABLE xxbcm_order_mgt ADD (new_order_line_amount NUMBER);
ALTER TABLE xxbcm_order_mgt ADD (new_invoice_amount NUMBER);

ALTER TABLE xxbcm_order_mgt MODIFY (supplier_name VARCHAR2(100));
ALTER TABLE xxbcm_order_mgt MODIFY (supp_contact_name VARCHAR2(100));
ALTER TABLE xxbcm_order_mgt MODIFY (supp_address VARCHAR2(200));
ALTER TABLE xxbcm_order_mgt MODIFY (supp_email VARCHAR2(50));
ALTER TABLE xxbcm_order_mgt MODIFY (invoice_hold_reason VARCHAR2(255));

------------- // Replace non-numerical values with numerical values in amount, and removing . and , //------------- 
UPDATE xxbcm_order_mgt SET 
    new_order_date = TO_DATE(order_date,'DD/MM/YYYY'),      -- converting values in order_date column TO DATE
    new_invoice_date = TO_DATE(invoice_date,'DD/MM/YYYY');  -- converting values in invoice_date column TO DATE
    
UPDATE xxbcm_order_mgt SET 
    new_order_status = order_status,
    new_invoice_status = invoice_status;
    
UPDATE xxbcm_order_mgt SET
    new_order_total_amount = TO_CHAR(order_total_amount, '999999999'),
    new_order_line_amount = TO_CHAR(order_line_amount, '999999999'),
    new_invoice_amount = TO_CHAR(invoice_amount, '999999999');
    
ALTER TABLE xxbcm_order_mgt DROP (
    order_date, invoice_date, order_status, invoice_status,
    order_total_amount, order_line_amount, invoice_amount
); -- dropping columns from xxbcm_order_mgt

ALTER TABLE xxbcm_order_mgt RENAME COLUMN new_order_date TO order_date; -- renaming the new column with the converted date to Order_date
ALTER TABLE xxbcm_order_mgt RENAME COLUMN new_invoice_date TO invoice_date; -- renaming the new column with the converted date to Invoice_date
ALTER TABLE xxbcm_order_mgt RENAME COLUMN new_order_status TO order_status;
ALTER TABLE xxbcm_order_mgt RENAME COLUMN new_invoice_status TO invoice_status;
ALTER TABLE xxbcm_order_mgt RENAME COLUMN new_order_total_amount TO order_total_amount;
ALTER TABLE xxbcm_order_mgt RENAME COLUMN new_order_line_amount TO order_line_amount;
ALTER TABLE xxbcm_order_mgt RENAME COLUMN new_invoice_amount TO invoice_amount;


------------- // CREATING SUPPLIER TABLE //------------- 
CREATE TABLE supplier (
    supplier_id  NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) CONSTRAINT supplier_pk PRIMARY KEY,
    supplier_name VARCHAR2(100),
    supp_contact_name VARCHAR2(100),
    supp_contact_number VARCHAR2(2000),
    supp_email VARCHAR2(50) CONSTRAINT supp_email_uk UNIQUE,
    supp_address VARCHAR2(200)
);

INSERT INTO supplier(supplier_name, supp_contact_name, supp_contact_number, supp_email, supp_address) 
SELECT DISTINCT supplier_name, supp_contact_name, supp_contact_number, supp_email, supp_address 
FROM xxbcm_order_mgt 
ORDER BY supplier_name;

------------- // CREATING INVOICE ISSUED TABLE //------------- 
CREATE TABLE invoice_issued (
    invoice_issued_id  NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) CONSTRAINT invoice_issued_pk PRIMARY KEY,
    invoice_ref VARCHAR2(2000),
    supplier_id,
    CONSTRAINT supplier_invoice_fk FOREIGN KEY (supplier_id) REFERENCES supplier(supplier_id)
);

INSERT INTO invoice_issued(invoice_ref, supplier_id) 
SELECT DISTINCT x.invoice_reference, s.supplier_id 
FROM xxbcm_order_mgt x, supplier s
WHERE x.supplier_name = s.supplier_name;

------------- // CREATING INVOICE DETAILS TABLE //------------- 
CREATE TABLE invoice_details (
    invoice_description VARCHAR2(2000),
    invoice_amount NUMBER,
    invoice_hold_reason VARCHAR2(255),
    invoice_issued_id,
    CONSTRAINT inv_details_to_issued_fk FOREIGN KEY (invoice_issued_id) REFERENCES invoice_issued(invoice_issued_id)
);

INSERT INTO invoice_details(invoice_description, invoice_amount, invoice_hold_reason, invoice_issued_id) 
SELECT DISTINCT x.invoice_description, x.invoice_amount, x.invoice_hold_reason, invi.invoice_issued_id 
FROM xxbcm_order_mgt x, invoice_issued invi
WHERE x.invoice_reference = invi.invoice_ref;

------------- // CREATING INVOICE STATS TABLE //------------- 
CREATE TABLE invoice_stats (
    invoice_date DATE,
    invoice_status VARCHAR2(10),
    invoice_issued_id,
    CONSTRAINT inv_stats_to_issued_fk FOREIGN KEY (invoice_issued_id) REFERENCES invoice_issued(invoice_issued_id)
);

INSERT INTO invoice_stats(invoice_date, invoice_status, invoice_issued_id) 
SELECT DISTINCT x.invoice_date, x.invoice_status, invi.invoice_issued_id 
FROM xxbcm_order_mgt x, invoice_issued invi
WHERE x.invoice_reference = invi.invoice_ref;

------------- // CREATING ORDER ISSUED TABLE //------------- 
CREATE TABLE order_issued (
    order_issued_id  NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) CONSTRAINT order_issued_pk PRIMARY KEY,
    order_ref VARCHAR2(2000),
    supplier_id,
    CONSTRAINT supplier_order_fk FOREIGN KEY (supplier_id) REFERENCES supplier(supplier_id)
);

INSERT INTO order_issued(order_ref, supplier_id) 
SELECT DISTINCT x.order_ref, s.supplier_id 
FROM xxbcm_order_mgt x, supplier s
WHERE x.supplier_name = s.supplier_name;

------------- // CREATING ORDER DETAILS TABLE //------------- 
CREATE TABLE order_details (
    order_description VARCHAR2(2000),
    order_line_amount NUMBER,
    order_total_amount NUMBER,
    order_issued_id,
    CONSTRAINT or_details_to_issued_fk FOREIGN KEY (order_issued_id) REFERENCES order_issued(order_issued_id)
);

INSERT INTO order_details(order_description, order_line_amount, order_total_amount, order_issued_id) 
SELECT DISTINCT x.order_description, x.order_line_amount, x.order_total_amount, ordi.order_issued_id 
FROM xxbcm_order_mgt x, order_issued ordi
WHERE x.order_ref = ordi.order_ref;

------------- // CREATING ORDER STATS TABLE //------------- 
CREATE TABLE order_stats (
    order_date DATE,
    order_status VARCHAR2(10),
    order_issued_id,
    CONSTRAINT or_stats_to_issued_fk FOREIGN KEY (order_issued_id) REFERENCES order_issued(order_issued_id)
);

INSERT INTO order_stats(order_date, order_status, order_issued_id) 
SELECT DISTINCT x.order_date, x.order_status, ordi.order_issued_id 
FROM xxbcm_order_mgt x, order_issued ordi
WHERE x.order_ref = ordi.order_ref;


------------- // QUESTION 4 //------------- 
SELECT DISTINCT
    TO_NUMBER(REGEXP_REPLACE(ordi.order_ref, '[^0-9]+', '')) "Order Reference", 
    ords.order_date "Order Period",
    UPPER(SUBSTR(s.supplier_name,1,1))||LOWER(SUBSTR(s.supplier_name,2)) "Supplier Name",
    ords.order_status "Order Status",
    invi.invoice_ref "Invoice Reference"
FROM 
    order_issued ordi, order_stats ords, supplier s, invoice_issued invi
WHERE 
    ordi.order_issued_id = ords.order_issued_id
    AND ordi.supplier_id = s.supplier_id
    AND s.supplier_id = invi.supplier_id;

------------- // QUESTION 5 //------------- 
SELECT DISTINCT
    TO_NUMBER(REGEXP_REPLACE(ordi.order_ref, '[^0-9]+', '')) "Order Reference",
    TO_CHAR(TO_DATE(ords.order_date, 'DD-MON-YY'), 'Month DD, YYYY') "Order Period",
    UPPER(s.supplier_name) "Supplier Name",
--    MAX(ordd.order_total_amount) "Order Total Amount",
    ords.order_status "Order Status"
--    invi.invoice_ref "Invoice Reference"
FROM 
    order_issued ordi, order_stats ords, supplier s, invoice_issued invi, order_details ordd
WHERE
    ordi.order_issued_id = ords.order_issued_id
    AND ordi.supplier_id = s.supplier_id
    AND ordi.order_issued_id = ordd.order_issued_id
    AND s.supplier_id = invi.supplier_id;
    
    
--TESTING question 5 max()            
SELECT 
    ordi.order_ref,
    MAX(ordd.order_total_amount) "Order Total Amount"
FROM    
    order_issued ordi
INNER JOIN 
    order_details ordd
    ON ordi.order_issued_id = ordd.order_issued_id
    WHERE ordd.order_total_amount IS NOT NULL
    GROUP BY ordi.order_ref
    ORDER BY "Order Total Amount" DESC
    FETCH FIRST 1 ROWS ONLY;


--UPDATE xxbcm_order_mgt
--SELECT DISTINCT TO_NUMBER(order_total_amount, '999999999') "Order Total Amount" FROM xxbcm_order_mgt WHERE order_total_amount IS NOT NULL ORDER BY "Order Total Amount" DESC;
--SELECT TO_CHAR(order_total, '999,999,999', '999,999,999.00') "Order Total Amount" FROM testing;
--
--CREATE TABLE testing (
--    order_total VARCHAR2(2000) 
--);
--drop table testing;
--INSERT INTO testing (order_total) VALUES ('5,819,625');
--select * from testing;

   
------------- // QUESTION 6 //------------- 
SELECT DISTINCT
    s.supplier_name "Supplier Name",
    s.supp_contact_name "Supplier Contact Name",
--    s.supp_contact_number "Supplier Contact No. 1",
--    s.supp_contact_number "Supplier Contact No. 2",
    TO_CHAR(ordd.order_total_amount, '99,999,990.00') "Order Total Amount"
FROM 
    supplier s, order_details ordd, order_issued ordi
WHERE
    s.supplier_id = ordi.supplier_id
    AND ordi.order_issued_id = ordd.order_issued_id;

